<?php

// declare(strict_types=1);
// header('Content-Type: application/json');


$flag = isset($this->viewData['flag']) ? $this->viewData['flag'] : null;

if ($flag == "userlistdata") {

    $page = isset($this->viewData['page']) ? max((int)$this->viewData['page'], 1) : 1; // Ensure valid page number
    $limit = isset($this->viewData['limit']) ? max((int)$this->viewData['limit'], 1) : 20; // Ensure valid limit 

     $res = UserManageModel::fetchUsersData();
     echo json_encode($res);
     return;
    // $page = isset($this->viewData['page']) ? max((int)$this->viewData['page'], 1) : 1; // Ensure valid page number
    // $limit = isset($this->viewData['limit']) ? max((int)$this->viewData['limit'], 1) : 20; // Ensure valid limit 
    // $result = (new UserManageModel())->FetchUserlistData($page, $limit);

    //   echo json_encode([
    //     'users' => $result['data'],
    //     'totalPages' => ceil($result['total'] / $limit)
    // ]);
}

if($flag === "searchUserlistData") {
    
    $uid = isset($this->viewData['uid']) ? max($this->viewData['uid'],0) : '';
    $states = isset($this->viewData['state']) ? max($this->viewData['state'],0) : '';
    $recharge_level = isset($this->viewData['recharge_level']) ? max($this->viewData['recharge_level'],0) : '';
    $startdate = isset($this->viewData['startdate']) ? max($this->viewData['startdate'],0) : '';
    $enddate = isset($this->viewData['enddate']) ? max($this->viewData['enddate'],0) : '';
  
    
    if(empty($uid)) {
        echo json_encode(["status" => "error", "data" => "Please select a user."]);
        return; 
    }

    $res = UserManageModel::searchUserData(["uid" => $uid,"state" => $states,"recharge_level" =>  $recharge_level,"start_date" => $startdate, "end_date" => $enddate]);
     echo json_encode($res);
     return;


}

if ($flag == "filteruserlist") {
    $uid = isset($this->viewData['username']) ? $this->viewData['username'] : '';
    $states = isset($this->viewData['states']) ? $this->viewData['states'] : '';
    $usernameCheck = (new BusinessFlowModel())->getUserIdByUsername($uid);
    $startdate = isset($this->viewData['startdate']) ? $this->viewData['startdate'] : '';
    $enddate = isset($this->viewData['enddate']) ? $this->viewData['enddate'] : '';
    $page = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
    $limit = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 20;



     if (!empty($usernameCheck) && $usernameCheck != null) {
         $username = $usernameCheck[0]['uid'];
         $sunquery = (new UserManageModel())->FilterUserlistDataSubQuery($username,$states, $startdate, $enddate);
         $result = (new UserManageModel())->Filteruserlist($sunquery,$page,$limit) ?? [];
        //  echo json_encode([
        //     // 'sql' => $result['sql'],
        //      'userlists' => $result,
        //      //'totalPages' => ceil($result['total'] / $limit)
        //  ]);
     }else{
        $sunquery = (new UserManageModel())->FilterUserlistDataSubQuery($uid,$states, $startdate, $enddate);
         $result = (new UserManageModel())->Filteruserlist($sunquery,$page,$limit) ?? []; 
        //  echo json_encode([
        //     // 'sql' => $result['sql'],
        //      'userlists' => $result,
        //     // 'totalPages' => ceil($result['total'] / $limit)
        //  ]);
     }
   
     $bigArr = [];
     foreach ($result['data'] as $data) {
     
         $referals = (new UserManageModel())->getDirectReferrals($data['agent_id']);
         $subor = (new UserManageModel())->getSubordinate($data['agent_id']);
         $totalsubordinate = (new UserManageModel())->Fetchsubordinates($data['uid']);

        //    $relationship = '';
            $subordinates = '';
        //    if (!empty($data['agent_name']) && $data['agent_name'] !== "*****" && !empty($subor))  {
        //      $relationship = $data['agent_name'] . ' ' . $referals . ' ' . $data['nickname'];
        //      $subordinates = (count($subor) > 1) ? '...' : "";
        //  } elseif ($data['agent_name'] && empty($subor)) {
        //     $relationship = "Top Agent";
        // } else {
        //      $relationship = '';
        //     $subordinates = '';
        // }

        //   $data['subordinates'] = $subor;
         $data['sub_count'] = $totalsubordinate;
        //  $data['relationship'] = $relationship;
        //   $data['subordinates'] = $subordinates;
         $bigArr [] = $data;
      
     }

    echo json_encode([
       // 'sql' => $result['sql'],
        'userlists' => $bigArr,
        'totalPages' => ceil($result['total'] / $limit)
    ]);
}


if ($flag  == "fetchRebatedata") {
    $result = (new UserManageModel())->FetchRebateData() ?? [];
    echo json_encode($result);
}


if ($flag == "addAgent") {

    $data = isset($this->viewData['data']) ? $this->viewData['data'] : '';
    //  $data = urldecode($data);
     parse_str($data, $parsedData);
     $result = (new UserManageModel())->validateRegister($data) ?? [];
    // if ($result == []) {
    //     $dateTime = date("Y-m-d H:i:s");
    //     $account_type = 2;
    //     $rebatelist =  (new UserManageModel())->fetchquotaData($parsedData['agentrebate']);
    //     $nickname = (new UserManageModel())->generateRandomNickname();
    //     $userstate = 1;
    //     $userstatus = 1;
    //     $type = "email";
    //     $uniqueId = bin2hex(random_bytes(12));
    //     $datas = [
    //         'unique_id' =>$uniqueId,
    //         'username' => $parsedData['agentname'],
    //         'nickname' => $nickname,
    //         'agent_name' =>  $parsedData['agentname'],
    //         'upassword' =>  password_hash($parsedData['agentpassword'], PASSWORD_BCRYPT),
    //         'email' =>  $parsedData['agentemail'],
    //         'rebate' =>  $parsedData['agentrebate'],
    //         'account_type' => $account_type,
    //         'created_at' => $dateTime,
    //         'user_state' => $userstate,
    //         'user_status' => $userstatus,
    //         'rebate_list' => $rebatelist,
    //         'reg_type' =>  $type,
    //         'agent_level' => '*****',
    //     ];

        
        // return [
        //     (string) bin2hex(random_bytes(12)), //unique_id
        //     (string) $parsedData['agentname'], //username
        //     (string) 1, //username_verified
        //     (string) $nickname,  //nickname
        //     (string) $email , // email
        //     (string) password_hash($parsedData['agentpassword'], PASSWORD_BCRYPT), //password,
        //     (string) 1, //email_verified,
        //     (string) '*****',//dob,
        //     (string) $country_code,
        //     (string) '*****'.bin2hex(random_bytes(10)), // contact
        //     (string) 0,
        //     (string) '/assets/avators/profile.png', // avatar
        //     (string) '*****', //agent_id,
        //     (string) '*****', //agent_name,
        //     (string) '*****', //agent_level,
        //     (string) '*****', //referral_code,
        //     (string) 0.0000, //balance,
        //     (string) $rebate, //rebate,
        //     (string) '*****', //last_login,
        //     (string) 0, //login_attempt
        //     (string) $this->getServerId(), //ip_address,
        //     (string) '*****', //money_password,
        //     (string) '*****', //browser_info,
        //     (string) '*****', //device_info,
        //     (string) 1, //user_state,   1:enabled, 2:suspended, 3:forbidden, 4:blocked
        //     (string) 1, //user_status,  1:active,  0:inactive
        //     (string) 2, //account_type, 1:customer, 2:TobAgent, 3:sub-agent
        //     (string) '*****', //idcard_number,
        //     (string) '*****', //idcard_front,
        //     (string) '*****', //idcard_back,
        //     (string) '*****', //login_token,
        //     (string) 0, // current_action,    1:loggedin,  0:logged out
        //     (string) 1, // withdral_level,    1:range(1-20,000) 2: range(1-50,000) , 3:range(1-100,000)
        //     (string) 1, //recharge_level,
        //     (string) '*****', //security_question,
        //     (string) '*****', //security_answer,
        //     (string) '*****', //auth_type,
        //     (string) '*****', //isOtpEnable,
        //     (string) '*****', //isSmsEnable,
        //     (string) '*****', //isGoogleAuthEnable,
        //     (string) $rebateList, //rebate_list,
        //     (string) '*****', //blocked_lotteries,
        //     (string) '*****', //linker,
        //     (string) '*****', //email_verification_token
        //     (string) '*****', //contact_verification_token
        //     (string) '*****', //reset_token,
        //     (string) date("Y-m-d"), // created at
        //     (string) '*****', //updated_at,
        //     (string) $type
        // ];

       // $result = (new UserManageModel())->AddAgentData($datas) ?? [];
    //}

     print_r($data);
}


if ($flag == "fetchTopAgentV1") {

    $page = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
    $limit = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 20;
    $result = (new UserManageModel())->FetchTopAgentData($page, $limit) ?? [];

    $usersLists = [];
    foreach ($result['data'] as $data) {
      //  $userlogins = (new UserManageModel())->countUserLogs($data['uid']);
        $totalsubordinate = (new UserManageModel())->Fetchsubordinates($data['uid']);
        $relationship = '';
        if ($data['account_type'] == 2) {
            $relationship = "Top Agent";
        }

        // Add data to the user list
        $usersLists[] = array_merge($data, [
            //'userlogins' => $userlogins,
            'totalsubordinate' => $totalsubordinate,
            'relationship' => $relationship,
        ]);
    }

    echo json_encode([
        'topagent' => $usersLists,
        'totalPages' => ceil($result['total'] / $limit)
    ]);
}

if ($flag  == "userlogsdata") {

    $page = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
    $limit = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 20;
    $result = (new UserManageModel())->FetchUserlogsData($page, $limit) ?? [];
   
    echo json_encode([
        'userlogs' => $result['data'],
        'totalPages' => ceil($result['total'] / $limit)
    ]);
}

if ($flag == "filterUserlogs") {
    $username = isset($this->viewData['usernamelog']) ? $this->viewData['usernamelog'] : '';
    $usernameCheck = (new BusinessFlowModel())->getUserIdByUsername($username);
    $startdate = isset($this->viewData['startdate']) ? $this->viewData['startdate'] : '';
    $enddate = isset($this->viewData['enddate']) ? $this->viewData['enddate'] : '';
    $page = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
    $limit = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 20;
    if (!empty($usernameCheck) && $usernameCheck != null) {
        $usernamelog = $usernameCheck[0]['uid'];
        $sunquery = (new UserManageModel())->FilterUserlogsDataSubQuery($usernamelog, $startdate, $enddate);
        $result = (new UserManageModel())->Filteruserlogs($sunquery, $page, $limit) ?? [];
        echo json_encode([
             'sql' => $result['sql'],
             'userloggs' => $result['data'],
             'totalPages' =>  ceil($result['total'] / $limit)
        ]);
    } else {

        $sunquery = (new UserManageModel())->FilterUserlogsDataSubQuery($username, $startdate, $enddate);
        $result = (new UserManageModel())->Filteruserlogs($sunquery, $page, $limit) ?? [];

        echo json_encode([
            'sql' => $result['sql'],
            'userloggs' => $result['data'],
            'totalPages' => ceil($result['total'] / $limit)
        ]);
    }
}

if ($flag == "getuserrebate") {

    $uid = isset($this->viewData['uid']) ? $this->viewData['uid'] : '';
    $result = (new UserManageModel())->fetchUserRebateList($uid) ?? [];
    echo json_encode($result);
}

if ($flag == "updateUsedquota") {

    $uid = isset($this->viewData['uid']) ? $this->viewData['uid'] : '';
    $bonus_group = isset($this->viewData['bonus']) ? $this->viewData['bonus'] : '';
    $rebate_group = isset($this->viewData['rebate']) ? $this->viewData['rebate'] : '';
    $quata_group = isset($this->viewData['quota']) ? $this->viewData['quota'] : '';
    $count_group = isset($this->viewData['count']) ? $this->viewData['count'] : '';

    function parseEncodedData($data)
    {
        $decodedData = urldecode($data); // Decode URL-encoded string
        return array_map('floatval', explode(',', $decodedData)); // Split into array and convert to float
    }
    $parsedBonus = parseEncodedData($bonus_group);
    $parsedRebate = parseEncodedData($rebate_group);
    $parsedQuota = parseEncodedData($quata_group);
    $parsedCount = parseEncodedData($count_group);

    // Define keys for the final structured data
    $keys = ['odds_group', 'rebate', 'quota', 'counts'];

    // Combine all parsed data into a structured array
    $results = [];
    foreach ($parsedBonus as $key => $value) {
        $row = [
            $keys[0] => $parsedBonus[$key] ?? null,
            $keys[1] => $parsedRebate[$key] ?? null,
            $keys[2] => $parsedQuota[$key] ?? null,
            $keys[3] => $parsedCount[$key] ?? null,
        ];
        $results[] = $row;
    }

    // Map the results to an array with keys
    $result = (new AgentManageModel())->UpdateUserquotaData(json_encode($results), $uid);
    echo json_encode($result);
}

if($flag == "fetchTopAgent"){
    $recharge_level = isset($this->viewData['recharge_level']) ? max((int)$this->viewData['recharge_level'], 0) : ""; // Ensure valid page number
    $state          = isset($this->viewData['state']) ? max((int)$this->viewData['state'], 0) : ""; // Ensure valid limit 
    $start_date     = isset($this->viewData['start_date']) ? max((int)$this->viewData['start_date'], 0) : ""; // Ensure valid page number
    $end_date       = isset($this->viewData['end_date']) ? max((int)$this->viewData['end_date'], 0) : ""; // Ensure valid limit 
    $page           = isset($this->viewData['page']) ? max((int)$this->viewData['page'], 1) : ""; // Ensure valid page number
    $limit          = isset($this->viewData['limit']) ? max((int)$this->viewData['limit'], 1) : 20; // Ensure valid limit 


    // echo json_encode(["recharge_level" => $recharge_level,"user_state" => $state,"start_date" => $start_date,"end_date" => $end_date]);

    // return;

     $res = UserManageModel::fetchTopAgents(["recharge_level" => $recharge_level,"state" => $state,"start_date" => $start_date,"end_date" => $end_date], $page , $limit);
     echo json_encode($res);

    return;
}
if($flag == "fetchUserData"){
      $page = isset($this->viewData['page']) ? max((int)$this->viewData['page'], 1) : 1; // Ensure valid page number
    $limit = isset($this->viewData['limit']) ? max((int)$this->viewData['limit'], 1) : 20; // Ensure valid limit 

     $res = UserManageModel::fetchTopAgents($page,$limit);
     echo json_encode($res);

    return;
}

if ($flag == "fetchsubagent") {
    $user_id   = $this->viewData['user_id'];
    $page = isset($this->viewData['page']) ? max((int)$this->viewData['page'], 1) : 1; // Ensure valid page number
    $limit = isset($this->viewData['limit']) ? max((int)$this->viewData['limit'], 1) : 20; // Ensure valid limit 

     $res = UserManageModel::fetchAgentSubs($user_id);
     echo json_encode($res);

    return;
  
    // $result =  (new UserManageModel())->FetchSubAgents($nickname,$page,$limit);
    // echo json_encode([
    //     'subagent' => $result['data'],
    //     'totalPages' => ceil($result['total'] / $limit)
    // ]);
   
}else if($flag == "blockUser"){

    $user_id = $this->viewData["user_id"];
    $res     = UserManageModel::blockUserData($user_id);
    echo json_encode($res);
    return;
}else if($flag == "deleteUser"){

    $user_id = $this->viewData["user_id"];
    $res     = UserManageModel::deleteUserData($user_id);
    echo json_encode($res);
    return;
}else if($flag == "fetchUserLotteries"){
;    $user_id = $this->viewData["user_id"];
    $res     = UserManageModel::fetchUserLotteries($user_id);
    echo json_encode($res);
}else if($flag == "updateLotteryState"){
    $user_id    = $this->viewData["user_id"];
    $lottery_id = $this->viewData["lottery_id"];
    
    $res        = UserManageModel::update_lottery_stat_for_user($user_id,$lottery_id);

    echo json_encode($res);
}else if($flag === "fetchUserLogs"){


    $user_id    = $this->viewData["user_id"];
    $res        = UserManageModel::fetchUserLogs($user_id);
    echo json_encode($res);

  

}else if($flag == "blockUserIp"){
    $ip_id  = $this->viewData['ulog_id'];
    $uid    = $this->viewData['user_id'];
    $res    = UserManageModel::block_user_ip($uid, $ip_id);
    echo json_encode($res);
}else if($flag === "fetchUserInfo"){

    $user_id         = $this->viewData['user_id'];
    $user_id         = intval($user_id);
    $data            = UserManageModel::FetchUserData($user_id);
    // $userData        = UserManageModel::getBankAccounts($user_id );
    // $withdrawalCount = UserManageModel::withdrawalCount($user_id);
  

    echo json_encode($data);
}else if($flag === "updateUserData"){
    $user_id         = $this->viewData["user_id"];
    $depositLimit    = $this->viewData["depositLimit"];
    $withdrawalLimit = $this->viewData["withdrawalLimit"];
    $rebate          = $this->viewData["rebate"];
    $state           = $this->viewData["state"];
    $dailyBettingTotalLimit = $this->viewData["dailyBettingTotalLimit"];

    $data = UserManageModel::updateUserInfo($user_id, $depositLimit,$withdrawalLimit, $rebate,$state,$dailyBettingTotalLimit);

    echo json_encode($data);
}else if($flag === "fetchUserRel"){
    $user_id   = $this->viewData["user_id"];
    $data = UserManageModel::fetch_user_rel($user_id);

    echo json_encode($data);
    return;
}



if ($flag == "fetchaccountchange") {

    $uid = isset($this->viewData['uid']) ? $this->viewData['uid'] : '';
    $page = isset($this->viewData['page']) ? max((int)$this->viewData['page'], 1) : 1; // Ensure valid page number
    $limit = isset($this->viewData['limit']) ? max((int)$this->viewData['limit'], 1) : 20; // Ensure valid limit 
    $result =  (new UserManageModel())->FetchUserAccountChange($uid,$page,$limit);
    echo json_encode([
        'account' => $result['data'],
        'totalPages' => ceil($result['total'] / $limit)
    ]);
   
}

if ($flag == "filterchange") {
    $uid = isset($this->viewData['uid']) ? $this->viewData['uid'] : '';
    $ordertype = isset($this->viewData['ordertype']) ? $this->viewData['ordertype'] : '';
    $page = isset($this->viewData['page']) ? max((int)$this->viewData['page'], 1) : 1; // Ensure valid page number
    $limit = isset($this->viewData['limit']) ? max((int)$this->viewData['limit'], 1) : 20; // Ensure valid limit 
    $startdate = isset($this->viewData['startdate']) ? $this->viewData['startdate'] : '';
    $enddate = isset($this->viewData['enddate']) ? $this->viewData['enddate'] : '';
    $subquery =  (new UserManageModel())->FilterChangeDataSubQuery($ordertype,$startdate,$enddate);
    $result =  (new UserManageModel())->FilterUserAccountChange($subquery,$uid,$page,$limit);
    echo json_encode([
        'filteraccount' => $result['data'],
        'totalPages' => ceil($result['total'] / $limit)
    ]);
   
}






