<?php
// declare(strict_types=1);
// header('Content-Type: application/json');
ini_set("display_errors",1);

$flag = isset($this->viewData['flag']) ? $this->viewData['flag'] : null;


if ($flag == "fetchfinance") {
    $page = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
    $limit = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 20;
    $result = (new FinancialManageModel())->FinancialDataRecords($page, $limit) ?? [];
    echo json_encode([
        'finance' => $result['data'],
        'totalPages' => ceil($result['total'] / $limit),
    ]);
}


if ($flag == "filterfinance") {

    $uid             = isset($this->viewData['uid']) ?  $this->viewData['uid'] : "";
    $states          = isset($this->viewData['status']) ?  $this->viewData['status'] : "";
    $startdate       = isset($this->viewData['startdate']) ? $this->viewData['startdate'] : "";
    $enddate         = isset($this->viewData['enddate']) ?  $this->viewData['enddate'] : "";
    $page            = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
    $limit           = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 20;
    $usernameCheck = (new BusinessFlowModel())->getUserIdByUsername($uid);
    $username = !empty($usernameCheck) ? $usernameCheck[0]['uid'] : $uid;
    $subquery = (new FinancialManageModel())->Financialsubquery($username,$states,$startdate,$enddate) ?? [];
    $result = (new FinancialManageModel())->FilterFinancialData($subquery,$page,$limit) ?? [];
    echo json_encode([
        'finances' => $result['data'],
        'totalPages' => ceil($result['total'] / $limit),
    ]);
}


if ($flag == "addmoney") {
    $depositetype = isset($this->viewData['depositetype']) ? (int) $this->viewData['depositetype'] : "";
    $uid = isset($this->viewData['uid']) ? (int) $this->viewData['uid'] :"";
    $amount = isset($this->viewData['amount']) ? (float)$this->viewData['amount'] : "";
    $username = isset($this->viewData['approvedby']) ? $this->viewData['approvedby'] : "";
    $review = urldecode(isset($this->viewData['review'])) ? urldecode($this->viewData['review']) : "";
    $username =  urldecode($username);
     $result = (new FinancialManageModel())->addMoneyData($depositetype,$uid,$amount,$username,$review) ?? [];
    echo json_encode($result);
}


if ($flag == "fetchDeposit") {
    $page = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
    $limit = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 20;
    $result = (new FinancialManageModel())->DepositDataRecords($page, $limit) ?? [];
    echo json_encode([
        'deposit' => $result['data'],
        'totalPages' => ceil($result['total'] / $limit),
    ]);
}


if ($flag == "filterdeposit") {

    $uid = isset($this->viewData['uid']) ?  $this->viewData['uid'] : "";
    $states = isset($this->viewData['states']) ?  $this->viewData['states'] : "";
    $depositids = isset($this->viewData['depositid']) ?  $this->viewData['depositid'] : "";
    $depostatus = isset($this->viewData['depostatus']) ?  $this->viewData['depostatus'] : "";
    $startdate = isset($this->viewData['startdate']) ? $this->viewData['startdate'] : "";
    $enddate = isset($this->viewData['enddate']) ?  $this->viewData['enddate'] : "";
    $page = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
    $limit = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 20;
    $usernameCheck = (new BusinessFlowModel())->getUserIdByUsername($uid);
    $username = !empty($usernameCheck) ? $usernameCheck[0]['uid'] : $uid;
    $subquery = (new FinancialManageModel())->Depositsubquery($username,$states,$depositids,$depostatus,$startdate,$enddate) ?? [];
    $result = (new FinancialManageModel())->FilterDepositData($subquery,$page,$limit) ?? [];
    echo json_encode([
        'deposits' => $result['data'],
        'totalPages' => ceil($result['total'] / $limit),
    ]);
}
      

if ($flag == "fetchwithdraw") {
    $partnerID = isset($this->viewData['partner_id']) ? (int) $this->viewData['partner_id'] : 0;
    $page      = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
    $limit     = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 10;
    $result    = (new FinancialManageModel())->WithrawalDataRecords($partnerID,$page) ?? [];
    echo json_encode($result);
}



