<?php
date_default_timezone_set('Asia/Singapore');
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$flag = isset($this->viewData['flag']) ? $this->viewData['flag'] : null;

if ($flag == "getAllgames") {
    $result = (new GameManageModel())->getAllGames();
    if($result){
        echo json_encode($result);
    } else {
        echo json_encode(['type'=>'error','message'=>'Some error occured']);
    }
} 

if ($flag == "getAllGamesLottery") {
    $result = (new GameManageModel())->getAllGamesLottery();
    if($result){
        echo json_encode($result);
    } else {
        echo json_encode(['type'=>'error','message'=>'Some error occured']);
    }
} 

if ($flag == "getLotteryGames") {
    $gameId = isset($this->viewData['gameId']) ? $this->viewData['gameId'] : '';
    $tableData = isset($this->viewData['tables']) ? $this->viewData['tables'] : '';
    $gametypes = isset($this->viewData['gametypes']) ? $this->viewData['gametypes'] : '';
    // $decodedUrl = urldecode($tableData);
    // $tables = json_decode($decodedUrl);
    $result = (new GameManageModel())->getLotteryGamesById($gameId,$tableData,$gametypes);
    echo json_encode(['bonus' => $result['data'] ]);
}

if ($flag == "updateoddstotalbets") {
    $gameId = isset($this->viewData['gameId']) ? $this->viewData['gameId'] : '';
    $gamemodel = isset($this->viewData['models']) ? $this->viewData['models'] : '';
    $newodds =isset($this->viewData['newodds']) ? $this->viewData['newodds'] : '';
    $oddpercent = isset($this->viewData['oddpercent']) ? $this->viewData['oddpercent'] : '';
    $newtotalbet =isset($this->viewData['newtotalbet']) ? $this->viewData['newtotalbet'] : '';
    $totalbetpercent =isset($this->viewData['totalbetpercent']) ? $this->viewData['totalbetpercent'] : '';
    $gametype = isset($this->viewData['gametype']) ? $this->viewData['gametype'] : '';
    $isSpecial = isset($this->viewData['isSpecial']) ? $this->viewData['isSpecial'] : '';
    $newodds = array_map('floatval', explode(',', $newodds));
    $newodds =   json_encode($newodds);
    $result =  GameManageModel::UpdateOddsTotalbets($gameId,$gamemodel,$newodds,$oddpercent,$newtotalbet,$totalbetpercent,$gametype,$isSpecial);
    echo json_encode($result);
}

if ($flag == "resettotalbet") {
    $gameId = isset($this->viewData['gameId']) ? $this->viewData['gameId'] : '';
    $gamemodel = isset($this->viewData['models']) ? $this->viewData['models'] : '';
    $newtotalbet =isset($this->viewData['newtotalbet']) ? $this->viewData['newtotalbet'] : '';
    $totalbetpercent =isset($this->viewData['totalbetpercent']) ? $this->viewData['totalbetpercent'] : '';
    $gametype = isset($this->viewData['gametype']) ? $this->viewData['gametype'] : '';
    $result = (new GameManageModel())->ResetTotalbets($gameId,$gamemodel,$newtotalbet,$totalbetpercent,$gametype);
    echo json_encode($result);
}

if ($flag == "updategamestatus") {
    $gameId = isset($this->viewData['gameId']) ? $this->viewData['gameId'] : '';
    $gamemodel = isset($this->viewData['models']) ? $this->viewData['models'] : '';
    $gametate =isset($this->viewData['gametate']) ? $this->viewData['gametate'] : ''; 
    $result = (new GameManageModel())->UpdateGameStatus($gameId,$gamemodel,$gametate);
    echo json_encode($result);
}

if ($flag == "updategamegroup") {
    $gamegroupid = isset($this->viewData['gamegroupid']) ? $this->viewData['gamegroupid'] : '';
    $gametate =isset($this->viewData['gametate']) ? $this->viewData['gametate'] : ''; 
    $result = GameManageModel::UpdateGameGroup($gamegroupid,$gametate);
    echo json_encode($result);
}

if ($flag == "updategamelottery") {
    $lotteryid = isset($this->viewData['lotteryid']) ? $this->viewData['lotteryid'] : '';
    $gametate =isset($this->viewData['gametate']) ? $this->viewData['gametate'] : ''; 
    $result = GameManageModel::UpdateGameLotteryType($lotteryid,$gametate);
    echo json_encode($result);
}

if ($flag == "getallgametype") {
    $result = GameManageModel::GetAllGameTypes();
    echo json_encode($result);
}

if($flag == "getSpecificDraws") {
    $page = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
    $limit = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 50;
    $gameId = isset($this->viewData['gameId']) ? $this->viewData['gameId'] : '';
    $datefrom = isset($this->viewData['datefrom']) ? $this->viewData['datefrom'] : '';
    $dateto = isset($this->viewData['dateto']) ? $this->viewData['dateto'] : '';
    $result = (new GameManageModel())->filterGameDraws($page, $limit, $gameId, $datefrom, $dateto);
    echo json_encode([
        'gameDraws' => $result['data'],
        'totalPages' => ceil($result['total'] / $limit),
    ]);
}

if ($flag == "getDraws") {
    $game_id = isset($this->viewData['gameId']) ? max($this->viewData['gameId'],1) : 0;
    $limit = isset($this->viewData['limit'])  ? max($this->viewData['limit'] ,0) : 20;
    $page = isset($this->viewData['page']) ? max($this->viewData['page'],0)  : 0;
    $start_date = isset($this->viewData['start_date']) ? $this->viewData['start_date'] : "";
    $end_date = isset($this->viewData['end_date']) ?  $this->viewData['end_date'] : "";
    $issue_number = isset($this->viewData['issue_number']) ? $this->viewData['issue_number'] : "";
    $draw_status = isset($this->viewData['status']) ? $this->viewData['status'] : "";
    // echo json_encode(['game_id' => $game_id, 'limit' => $limit , 'page' => $page, 'start_date' => $start_date, 'end_date' => $end_date, 'issue_number' => $issue_number, 'draw_status' => $draw_status]);
    // return;
     if(empty($game_id))return ["status" => 'error', "data" => "Internal Server Error"];
    $result = GameManageModel::getDrawTableInfo($game_id,$issue_number,$draw_status,$start_date,$end_date,$page,$limit);
    echo json_encode($result );
    
}

if ($flag == "resetAllOdds") {
 $result = GameManageModel::resetAllOdds();
 echo json_encode($result); 
    
}

if ($flag == "lotteryexception") {
 $page = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1; // Ensure valid page number
 $limit = isset($this->viewData['limit']) ? (int)$this->viewData['limit'] :""; // Ensure valid limit
 $result = GameManageModel::lotteryExceptionData($page, $limit);
//  $gameTypeId  = GameManageModel::GamesMapIdTable($gametype = 1)[0];
//  $lotteryName = GameManageModel::getSingleLottery($gameTypeId['game_type'])['name'];
//  $lotteryid = $gameTypeId['game_type'];
//  $finalResults = [];
//  foreach ($result['data']  as $drawPeriodRow) {
//   $drawPeriod = $drawPeriodRow['period']; // assuming your `$result` has 'period' key
//     $counts = GameManageModel::getBetCounts($gameTypeId['bet_table']);
//     $finalResults[] = [
//         'period'          => $drawPeriod,
//         'lottery_name'    => $lotteryName,
//         'gametypeid'      => $gameTypeId['game_type'],
//         'total_count'     => $counts['total_count'],
//         'settled_count'   => $counts['settled_count'],
//         'unsettled_count' => $counts['unsettled_count'],
//         'timezone'       => $counts['timezone'],
//         'dates' => date('Y-m-d').' / '.date('H:i:s')
//         // 'state'          => GameManageModel::getBetState($drawPeriod, $gameTypeId['bet_table']),
//     ];
//     }
    echo json_encode([
      'lotexception' => $result['data'],
     'totalPages' => ceil($result['total'] / $limit),
    ]);
   
 }