<?php

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);



$flag = isset($this->viewData['flag']) ? $this->viewData['flag'] : null;

if ($flag == "getAllgames") {
    $result = (new GameManageModel())->getAllGames();
    if($result){
        echo json_encode($result);
    } else {
        echo json_encode(['type'=>'error','message'=>'Some error occured']);
    }
} 

if ($flag == "getAllGamesLottery") {
    $result = (new GameManageModel())->getAllGamesLottery();
    if($result){
        echo json_encode($result);
    } else {
        echo json_encode(['type'=>'error','message'=>'Some error occured']);
    }
} 

if ($flag == "getLotteryGames") {
    $gameId = isset($this->viewData['gameId']) ? $this->viewData['gameId'] : '';
    $tableData = isset($this->viewData['tables']) ? $this->viewData['tables'] : '';
    // $decodedUrl = urldecode($tableData);
    // $tables = json_decode($decodedUrl);
    $result = (new GameManageModel())->getLotteryGamesById($gameId,$tableData);
    echo json_encode([
        'bonus' => $result['data'],
    ]);
}


if ($flag == "updateoddstotalbets") {
    $gameId = isset($this->viewData['gameId']) ? $this->viewData['gameId'] : '';
    $gamemodel = isset($this->viewData['models']) ? $this->viewData['models'] : '';
    $newodds =isset($this->viewData['newodds']) ? $this->viewData['newodds'] : '';
    $oddpercent = isset($this->viewData['oddpercent']) ? $this->viewData['oddpercent'] : '';
    $newtotalbet =isset($this->viewData['newtotalbet']) ? $this->viewData['newtotalbet'] : '';
    $totalbetpercent =isset($this->viewData['totalbetpercent']) ? $this->viewData['totalbetpercent'] : '';
    $newodds = array_map('floatval', explode(',', $newodds));
    $newodds =   json_encode($newodds);
   $result = (new GameManageModel())->UpdateOddsTotalbets($gameId,$gamemodel,$newodds,$oddpercent,$newtotalbet,$totalbetpercent);
    echo json_encode($result);
}

if ($flag == "resettotalbet") {
    $gameId = isset($this->viewData['gameId']) ? $this->viewData['gameId'] : '';
    $gamemodel = isset($this->viewData['models']) ? $this->viewData['models'] : '';
    $newtotalbet =isset($this->viewData['newtotalbet']) ? $this->viewData['newtotalbet'] : '';
    $totalbetpercent =isset($this->viewData['totalbetpercent']) ? $this->viewData['totalbetpercent'] : '';   
    $result = (new GameManageModel())->ResetTotalbets($gameId,$gamemodel,$newtotalbet,$totalbetpercent);
    echo json_encode($result);
}

if ($flag == "updategamestatus") {
    $gameId = isset($this->viewData['gameId']) ? $this->viewData['gameId'] : '';
    $gamemodel = isset($this->viewData['models']) ? $this->viewData['models'] : '';
    $gametate =isset($this->viewData['gametate']) ? $this->viewData['gametate'] : ''; 
    $result = (new GameManageModel())->UpdateGameStatus($gameId,$gamemodel,$gametate);
    echo json_encode($result);
}



if($flag == "getSpecificDraws") {
    $page = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
    $limit = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 50;
    $gameId = isset($this->viewData['gameId']) ? $this->viewData['gameId'] : '';
    $datefrom = isset($this->viewData['datefrom']) ? $this->viewData['datefrom'] : '';
    $dateto = isset($this->viewData['dateto']) ? $this->viewData['dateto'] : '';
    $result = (new GameManageModel())->filterGameDraws($page, $limit, $gameId, $datefrom, $dateto);
    echo json_encode([
        'gameDraws' => $result['data'],
        'totalPages' => ceil($result['total'] / $limit),
    ]);
}

if ($flag == "getDraws") {
    $game_id = isset($this->viewData['gameId']) ? max($this->viewData['gameId'],1) : 0;
    $limit = isset($this->viewData['limit'])  ? max($this->viewData['limit'] ,0) : 20;
    $page = isset($this->viewData['page']) ? max($this->viewData['page'],0)  : 0;
    $start_date = isset($this->viewData['start_date']) ? $this->viewData['start_date'] : "";
    $end_date = isset($this->viewData['end_date']) ?  $this->viewData['end_date'] : "";
    $issue_number = isset($this->viewData['issue_number']) ? $this->viewData['issue_number'] : "";
    $draw_status = isset($this->viewData['status']) ? $this->viewData['status'] : "";
    // echo json_encode(['game_id' => $game_id, 'limit' => $limit , 'page' => $page, 'start_date' => $start_date, 'end_date' => $end_date, 'issue_number' => $issue_number, 'draw_status' => $draw_status]);
    // return;
     if(empty($game_id))return ["status" => 'error', "data" => "Internal Server Error"];
    $result = GameManageModel::getDrawTableInfo($game_id,$issue_number,$draw_status,$start_date,$end_date,$page,$limit);
    echo json_encode($result );
    
    }