<?php
declare(strict_types=1);
// header('Content-Type: application/json');


$flag = isset($this->viewData['flag']) ? $this->viewData['flag'] : null;

if ($flag == "getDraws") {
$game_id = isset($this->viewData['gameId']) ? max($this->viewData['gameId'],0) : 0;
$limit = isset($this->viewData['limit'])  ? max($this->viewData['limit'] ,0) : 20;
$page = isset($this->viewData['page']) ? max($this->viewData['page'],0)  : 0;
$start_date = isset($this->viewData['start_date']) ? $this->viewData['start_date'] : "";
$end_date = isset($this->viewData['end_date']) ?$this->viewData['end_date'] : "";
$issue_number = isset($this->viewData['issue_number']) ? $this->viewData['issue_number'] : "";



    $result = GameManageModel::getDrawTableInfo($game_id,$issue_number,$start_date,$end_date,$page,$limit);
    echo json_encode($result );

}




