<?php
session_start();
ini_set("display_error",1);
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

$flag = isset($this->viewData['flag']) ? $this->viewData['flag'] : null;

if($flag == "twofaenable"){
     $email = isset($this->viewData['email']) ?  $this->viewData['email'] : "";
     $result = GoogleAuthenticateModel::UpdategoogleAuth($email) ?? [];
    echo json_encode($result);
 }

 if($flag == "verifyotp"){
   $adminEmail = (new Controller)->getSeesion("isUserLoggedIn");
   $otpcode = isset($this->viewData['otpcode']) ?  $this->viewData['otpcode'] : "";
   $result = GoogleAuthenticateModel::VerifyOtpCode($adminEmail,$otpcode) ?? [];
  echo json_encode($result);
}

if($flag == "verifyloginotp"){
   $adminEmail = (new Controller)->getSeesion("userauthmethosid");
   $otpcodes = isset($this->viewData['otpcodes']) ? $this->viewData['otpcodes'] : "";
   $result = GoogleAuthenticateModel::GetSecreteCode($adminEmail,$otpcodes) ?? [];
   echo json_encode($result);
}

if($flag == "verifycodebyemail"){
   $emails = isset($this->viewData['otpcodes']) ? $this->viewData['otpcodes'] : "";
   $code = rand(100000, 999999);

    if (filter_var($emails, FILTER_VALIDATE_EMAIL)) {
        $mail = new PHPMailer(true);

        try {
            // SMTP config for Gmail
            $mail->isSMTP();
            $mail->Host       = 'smtp.gmail.com';
            $mail->SMTPAuth   = true;
            $mail->Username   = 'pneumalogoss@gmail.com';         // Your Gmail address
            $mail->Password   = 'uxoz rwmj exdm wesl';      // Gmail App Password
            $mail->SMTPSecure = 'tls';
            $mail->Port       = 587;

            // Email content
            $mail->setFrom('pneumalogoss@gmail.com', 'Enzerhub TestApp');
            $mail->addAddress($emails);
            $mail->Subject = 'Your Verification Code';
            $mail->Body    = "Your verification code is: $code";
            $mail->send();
            echo "Verification code sent to your email.";
             $adminEmail = (new Controller)->getSeesion("userauthmethosid");
             $result = GoogleAuthenticateModel::SignOptionUpdates($adminEmail,$code);
        } catch (Exception $e) {
            http_response_code(500);
            echo "Email failed: {$mail->ErrorInfo}";
        }
    } else {
        http_response_code(400);
        echo "Invalid email address.";
    }

}


if($flag == "verifyoption"){
   $adminEmail = (new Controller)->getSeesion("userauthmethosid");
  $otpcodes = isset($this->viewData['otpcodes']) ? $this->viewData['otpcodes'] : "";
   $result = GoogleAuthenticateModel::SignOptionVerify($adminEmail,$otpcodes); 
   echo json_encode($result);
}





 