<?php


$flag = isset($this->viewData['flag']) ? $this->viewData['flag'] : null;

if($flag == "fetchsms"){

    $page  = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
    $limit = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 20;
    $smsResult = PLatFormSettingModel::FetchSms($page, $limit);
    $smsRecords = $smsResult['data'] ?? [];
    $totalCount = $smsResult['total'] ?? 0;
    $sms_id = $smsRecords[0]['sms_id'];
    foreach ($smsRecords as &$record) {
    $provider = $record['sms_provider'] ?? '';
        switch ($provider) {
            case 'smsonlinegh':
                SmsProvider::getSmsGHBalance($provider);
                break;
            case 'smsarkesel':
                SmsProvider::getArkeselSMSBalance($provider);
                break;
            default:
                error_log("Unknown SMS provider: " . $provider);
                break;
          }
        }
     echo json_encode([
            'sms' => $smsRecords,
            'totalPages' => ceil($totalCount / $limit)
        ]);           
}

if($flag == "addprovider"){
     $smsprovider = isset($this->viewData['smsprovider']) ? $this->viewData['smsprovider'] : "";
     $sendename = isset($this->viewData['sendename']) ?($this->viewData['sendename']) : "";
     $sendename =  urldecode($sendename);
   //  strtoupper(urldecode($sendename))
     $result  = PLatFormSettingModel::InserIntoSms($smsprovider,$sendename);
     echo json_encode($result);
}

if($flag == "savepreferences"){
    $data = json_decode(file_get_contents("php://input"), true);
    $result  = PLatFormSettingModel::InserIntoSavePreferences($data);
    echo json_encode($result);
}

if($flag == "savesmspreferencestate"){
     $result  = PLatFormSettingModel::SaveStateSmsSettings();
     echo json_encode($result); 
}

if($flag =="fetchsmsprovider"){
    $results = PLatFormSettingModel::FetchSmsProviders();
    echo json_encode($results);
}

if($flag == "filtersms"){
    $smsprovider = isset($this->viewData['smsprovider']) ?  $this->viewData['smsprovider'] : "";
    $smsstatus = isset($this->viewData['smsstatus']) ?  $this->viewData['smsstatus'] : "";
    $startdate = isset($this->viewData['startdate']) ? $this->viewData['startdate'] : "";
    $enddate = isset($this->viewData['enddate']) ?  $this->viewData['enddate'] : "";
    $page = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
    $limit = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 20;
      $subquery = PLatFormSettingModel::Smssubquery($smsprovider,$smsstatus,$startdate,$enddate) ?? [];
      $result   = PLatFormSettingModel::FilterSmsData($subquery,$page,$limit) ?? [];
    echo json_encode([
        'sms' => $result['data'],
         'totalPages' => ceil($result['total'] / $limit),
    ]);
}

if($flag == "deletesms"){
     $smsid = isset($this->viewData['sms']) ? $this->viewData['sms'] : "";
     $result  = PLatFormSettingModel::DeleteSms($smsid);
     echo json_encode($result);
}

if($flag == "fetchemaildata"){

    $page  = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
    $limit = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 20;
    $smsResult = PLatFormSettingModel::fetchEmailData($page, $limit);
    $emailRecords = $smsResult['data'] ?? [];
     $totalCount = $smsResult['total'] ?? 0;
    // $sms_id = $smsRecords[0]['sms_id'];
    // foreach ($smsRecords as &$record) {
    // $provider = $record['sms_provider'] ?? '';
    //     if($provider === "smsonlinegh" ) {
    //         SmsProvider::getSmsGHBalance($provider);  
    //     }
    // }
    echo json_encode([
            'email' => $emailRecords,
            'totalPages' => ceil($totalCount / $limit)
        ]);           
}

if($flag == "emailaddprovider"){
     $emailprovider = isset($this->viewData['emailprovider']) ? $this->viewData['emailprovider'] : "";
     $sendename = isset($this->viewData['sendename']) ?($this->viewData['sendename']) : "";
     $sendename =  urldecode($sendename);
   //  strtoupper(urldecode($sendename))
     $result  = PLatFormSettingModel::InserIntoEmail($emailprovider,$sendename);
     echo json_encode($result);
}

if($flag == "savepreferencesemail"){
    $data = json_decode(file_get_contents("php://input"), true);
    $result  = PLatFormSettingModel::InserEmailSavePreferences($data);
    echo json_encode($result);
}

if($flag == "savedemailpreferencestate"){
     $result  = PLatFormSettingModel::SaveStateEmailSettings();
     echo json_encode($result); 
}

if($flag =="fetchemailprovider"){
    $results = PLatFormSettingModel::FetchEmailProviders();
    echo json_encode($results);
}

if($flag == "filteremail"){
    $emailprovider = isset($this->viewData['emailprovider']) ?  $this->viewData['emailprovider'] : "";
    $emailstatus = isset($this->viewData['emailstatus']) ?  $this->viewData['emailstatus'] : "";
    $startdate = isset($this->viewData['startdate']) ? $this->viewData['startdate'] : "";
    $enddate = isset($this->viewData['enddate']) ?  $this->viewData['enddate'] : "";
    $page = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
    $limit = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 20;
      $subquery = PLatFormSettingModel::Emailsubquery($emailprovider,$emailstatus,$startdate,$enddate) ?? [];
      $result   = PLatFormSettingModel::FilterEmailData($subquery,$page,$limit) ?? [];
    echo json_encode([
        'email' => $result['data'],
         'totalPages' => ceil($result['total'] / $limit),
    ]);
}


if($flag == "deleteemail"){
     $emailid = isset($this->viewData['email']) ? $this->viewData['email'] : "";
     $result  = PLatFormSettingModel::DeleteEmail($emailid);
     echo json_encode($result);
}









 