<?php
// declare(strict_types=1);
// header('Content-Type: application/json');


$flag = isset($this->viewData['flag']) ? $this->viewData['flag'] : null;

if ($flag == "userlinkdata") {

        $page = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
        $limit = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 20;
        $result = (new PromotionManageModel())->FetchUserlinkData($page, $limit) ?? [];
        echo json_encode([
            'userlinks' => $result["data"],
            'totalPages' => ceil($result['total'] / $limit)
        ]);
    
} 

if($flag  == "filterUserlinks"){

    
    $page = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
    $limit = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 20;
    $uid = isset($this->viewData['username']) ? $this->viewData['username'] : '';
    $startdate = isset($this->viewData['startdate']) ? $this->viewData['startdate'] : '';
    $enddate = isset($this->viewData['enddate']) ? $this->viewData['enddate'] : '';

    $usernameCheck = (new BusinessFlowModel())->getUserIdByUsername($uid);
    $username = !empty($usernameCheck) ? $usernameCheck[0]['uid'] : $uid;
    $subquery =   (new PromotionManageModel())->FilterUserlinksDataSubQuery($username, $startdate, $enddate) ;
    $result = (new PromotionManageModel())->FilterUserlinks($subquery,$page, $limit) ?? [];
 
    echo json_encode([
        'sql' => $result['sql'],
        'userlinkss' => $result['data'],
        'totalPages' => ceil($result['total'] / $limit)
    ]);
}
