<?php
// declare(strict_types=1);
// header('Content-Type: application/json');


$flag = isset($this->viewData['flag']) ? $this->viewData['flag'] : null;

if ($flag == "userlinkdata") {

        $page = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
        $limit = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 20;
        $result = (new PromotionManageModel())->FetchUserlinkData($page, $limit) ?? [];
        echo json_encode([
            'userlinks' => $result["data"],
            'totalPages' => ceil($result['total'] / $limit)
        ]);
    
} elseif($flag  == "filterUserlinks"){

    
    $page = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
    $limit = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 20;
    $username = isset($this->viewData['username']) ? $this->viewData['username'] : '';
    $realUsername = '';
    if (empty($username)) {
        $realUsername = $username;
    } else {
        $realUsername = (new BusinessFlowModel())->getUserIdByMixedValued($username);
        if ($realUsername == 0) {
            echo json_encode([
                'sql' => '',
                'userlinkss' => [],
                'totalPages' => 0
            ]);
            exit;
        }
    }


    $startdate = isset($this->viewData['startdate']) ? $this->viewData['startdate'] : '';
    $enddate = isset($this->viewData['enddate']) ? $this->viewData['enddate'] : '';
    $result = (new PromotionManageModel())->FilterUserlinks($page, $limit, $realUsername, $startdate, $enddate) ?? [];

    $bigArrlinks = [];
    foreach ($result['data'] as $data) {
        $username  = (new BusinessFlowModel())->getUsernameById($data['agent_id']);
        $data['username'] = $username;
        $bigArrlinks[] = $data;

    }

    echo json_encode([
        'sql' => $result['sql'],
        'userlinkss' => $bigArrlinks,
        'totalPages' => ceil($result['total'] / $limit)
    ]);
}
