<?php

declare(strict_types=1);
// header('Content-Type: application/json');


$flag = isset($this->viewData['flag']) ? $this->viewData['flag'] : null;

if ($flag == "fetchbankcard") {

    $uid = isset($this->viewData['uid']) ? (int) $this->viewData['uid'] : "";
    $bank_type = isset($this->viewData['bank_type']) ?  $this->viewData['bank_type'] : "";
    $card_number = isset($this->viewData['card_number']) ?  $this->viewData['card_number'] : "";
    $status = isset($this->viewData['status']) ?  $this->viewData['status'] : 0;
    $page = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
    $limit = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 20;
    $result =  UserBankManageModel::FetchBankcardlistData(["uid" => $uid, "bank_type" => $bank_type, "card_number" => $card_number, "status" => $status], $page, $limit);

    echo json_encode($result);
} else if ($flag === "search-bank-name") {
    $bank_type = isset($this->viewData['bank_type']) ? $this->viewData['bank_type'] : "";
    if (empty($bank_type)) return ["status" => "success", "data" => []];
    $result =  UserBankManageModel::fetchBankTypes($bank_type);
    echo json_encode($result);
    return;
}
if ($flag == "userpaymentmethod") {
    $page = isset($this->viewData['page']) ? (int) $this->viewData['page'] : 1;
    $limit = isset($this->viewData['limit']) ? (int) $this->viewData['limit'] : 20;

    $result = UserBankManageModel::FetchuserpaymentData($page, $limit);
    echo json_encode($result);
}
if ($flag == "getuserpaymentmethod") {
    $uid = isset($this->viewData['uid']) ? (int) $this->viewData['uid'] : "";
    $result = UserBankManageModel::fetchUserPaymentByUid($uid);
    echo json_encode($result);
}

if ($flag == "inactivepayment") {
    $uid = isset($this->viewData['uid']) ? (int) $this->viewData['uid'] : "";
    $bank_id = isset($this->viewData['bank_id']) ? (int) $this->viewData['bank_id'] : "";
    $result = UserBankManageModel::DeleteUserPaymentInactiveByUid($uid, $bank_id);
    echo json_encode($result);
}
