<?php
!(new SessionMan)->isUserLoggedIn() ? header("location:../") : "";
$adminEmail = (new SessionMan)->getSession("isUserLoggedIn");
?>
<!DOCTYPE html>
<html oncontextmenu="return falsex" lang="en" dir="ltr" data-bs-theme="light" data-color-theme="Blue_Theme"
  data-layout="vertical" data-boxed-layout="full" data-card="shadow">

<head>
  <!-- Required meta tags -->
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon icon-->
  <link rel="shortcut icon" type="image/png" href="<?php echo BASE_URL; ?>assets/images/logos/favicon.png" />
  <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/toast/toast.css" />
  <!-- Core Css -->
  <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/styles.css" />
  <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/chrometab.css" />
  <link rel="stylesheet" href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" />
  <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/sidebar.css" />
  <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/home.css" />
  <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/micromodal.css" />
  <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/homepage.css" />
  <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/modal.css" />
  <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/logofont.css" />
  <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/glowing.css" />
  <!-- <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/customtab.css" /> -->
     <!-- <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/theme.custom.css" /> -->
  <title>Limvo Admin</title>
<style>
.tab-container {
    display: flex;
    overflow-x: auto;
    white-space: nowrap;
    clip-path: inset(0px 0px -10px 0px); 
}

.tab-wrapper {
    display: flex;
    align-items: center;
}

.scroll-left,
.scroll-right {
    /* background: #f1f1f1; */
    border: none;
    cursor: pointer;
    z-index: 9999;
    padding:4px;
}

.arrows{
  padding:4px;
  font-size:25px;
  color:rgb(131,143,164,0.2)
}

.arrows:hover {
   padding:4px;
   position:relative;
   border-radius: 50%;
   background-color: #eee;
   color: #bbb;
}
.tabs-container::-webkit-scrollbar {
  display: none; /* Hide scrollbar (for Chrome, Safari) */
}
.tab-container::-webkit-scrollbar {
  display: none; /* Hide scrollbar (for Chrome, Safari) */
}

.tab-container::-webkit-scrollbar-thumb {
    background-color: #aaa;
    border-radius: 3px;
}
</style>

</head>

<body>
  <!-- Preloader -->
  <div class="preloader">
    <img src="<?php echo BASE_URL; ?>assets/images/logos/favicon.png" alt="loader" class="lds-ripple img-fluid" />
  </div>
  <div id="main-wrapper"  style="overflow: none;">
    <!-- Sidebar Start -->
    <aside class="left-sidebar with-vertical" style="background:#F9F9F9;z-index: 0;">
      <div><!-- ---------------------------------- -->
        <!-- Start Vertical Layout Sidebar -->
        <!-- ---------------------------------- -->
        <div class="brand-logo d-flex align-items-center justify-content-between" style="background-color: #fff;">
          <h1 class="grays" style="color:#bbb">Limvo&trade;</h1>
          <a href="javascript:void(0)" class="sidebartoggler ms-auto text-decoration-none fs-5 d-block d-xl-none">
            <i class="ti ti-x"></i>
          </a>
        </div>

        <nav class="" data-simplebar>
          <ul id="sidebarnav">

            <?php include 'sidebar.php' ?>
            <!-- <button id="theme-toggle">🌓 Toggle Theme</button> -->

          </ul>
        </nav>

        <div class="mb-1" style="background-color:redl;position: fixed;bottom: 0;left:0;">
             <div style="padding:12px;">
          <div class="p-3  bg-white-subtle rounded mt-3" style="position:relative;background-color:#fff;border-radius:10px;border:solid 1px #eee">
            <div class="hstack gap-3">
              <div class="john-img">
                <img
                  src="<?php echo BASE_URL; ?>assets/images/profile/user-1.jpg"
                  class="rounded-circle" width="40" height="40" alt="modernize-img" />
              </div>
              <div class="john-title">
                <h6 class="mb-0 fs-4 fw-semibold">Kofi Benson</h6>
                <span class="fs-2">Designer</span>
              </div>
              <button class="border-0 bg-transparent text-primary ms-auto" tabindex="0" type="button" aria-label="logout" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="logout">
                <div class="dropdown" aria-label="logout" data-bs-toggle="tooltip" data-bs-placement="top"
                  data-bs-title="Profile">
                  <a class="dropdown-toggles" href="javascript:void(0)" role="button" id="dropdownMenuLink-1"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <i class='bx bx-dots-vertical-rounded'></i>
                  </a>
                  <div class="dropdown-menu dropdown-menu-end " aria-labelledby="dropdownMenuLink-1"
                    style="box-shadow: rgba(149, 157, 165, 0.2) 0px 8px 24px;">
                    <a class="dropdown-item kanban-item-edit lang cursor-pointer d-flex align-items-center gap-1"
                      href="javascript:void(0);" value="en">
                      <i class='bx bx-user-check'></i>English
                    </a>
                    <a class="dropdown-item kanban-item-edit lang cursor-pointer d-flex align-items-center gap-1"
                      href="javascript:void(0);" value="zh">
                      <i class='bx bx-pencil'></i>Chinese
                    </a>
                    <a class="dropdown-item kanban-item-delete cursor-pointer d-flex align-items-center gap-1"
                      href="javascript:void(0);">
                      <i class="bx bx-trash fs-5"></i>Others
                    </a>
                  </div>
                </div>
              </button>
            </div>
          </div>

          <div class="btn-group p-3 mb-2 bg-white-subtle rounded " role="group" style="width:100%;border:solid 1px #eee;color:#bbb;background-color:#fff;">
            <button type="button" class="btn bg-white-subtle">
              <i class='bx bx-bell' style="font-size: 20px;"></i>
            </button>
            <button type="button" class="btn bg-white-subtle ">
              <a href="../auth/signout"> <i class='bx bx-power-off' style="font-size: 20px;"></i> </a>
            </button>
            <button type="button" class="btn bg-white-subtle ">
              <i class='bx bx-history' style="font-size: 20px;"></i>
            </button>
            <button type="button" class="btn bg-white-subtle peg">
              <i class='bx bx-cog' style="font-size: 20px;"></i>
            </button>
          </div>
          </div>

        </div>
      </div>
    </aside>

    
    <div class="page-wrapper"  style="overflow: hidden;">
      <div class="containe-fluid">

        <div class="surface">
        
          <div class="mock-browser">
          
            <div class="chrome-tabs tab-wrapper" style="--tab-content-margin: 9px">
            <div class="scroll-left arrow-btn" ><i class='bx bx-chevron-left arrows' ></i></div>
              <div class="chrome-tabs-content tab-container">
                <div class="chrome-tab" id="tabhead" active>
                  <div class="chrome-tab-dividers"></div>
                  <div class="chrome-tab-background">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg">
                      <defs>
                        <symbol id="chrome-tab-geometry-left" viewBox="0 0 214 36">
                          <path d="M17 0h197v36H0v-2c4.5 0 9-3.5 9-8V8c0-4.5 3.5-8 8-8z" />
                        </symbol>
                        <symbol id="chrome-tab-geometry-right" viewBox="0 0 214 36">
                          <use xlink:href="#chrome-tab-geometry-left" />
                        </symbol>
                        <clipPath id="crop">
                          <rect class="mask" width="100%" height="100%" x="0" />
                        </clipPath>
                      </defs>
                      <svg width="52%" height="100%">
                        <use xlink:href="#chrome-tab-geometry-left" width="214" height="36"
                          class="chrome-tab-geometry" />
                      </svg>
                      <g transform="scale(-1, 1)">
                        <svg width="52%" height="100%" x="-100%" y="0">
                          <use xlink:href="#chrome-tab-geometry-right" width="214" height="36"
                            class="chrome-tab-geometry" />
                        </svg>
                      </g>
                    </svg>
                  </div>
                  <div class="chrome-tab-content">
                    <div class="chrome-tab-favicon" style="
                    background-image: url('demo/images/google-favicon.ico');
                  "></div>
                    <div class="chrome-tab-title">Dashboard</div>
                    <div class="chrome-tab-holder" hidden>home</div>
                    <div class="chrome-tab-drag-handle chromclass"></div>
                    <div class="chrome-tab-close" hidden></div>
                  </div>
                </div>
              </div>
            <span class="scroll-right arrow-btn"><i class='bx bx-chevron-right arrows'></i></span>
              <div class="chrome-tabs-bottom-bar"></div>
              <!-- Styles to prevent flash after JS initialization -->
            </div>
            <!-- <div class="chrome-tabs-optional-shadow-below-bottom-bar"></div> -->
        
          </div>
        
        </div>

        <div class="rowr" style="padding:0px;overflow-x:hidden;">

          <div class="chrome__tab home">
            <?php include "tabs/home.php" ?>
          </div>

          <div class="chrome__tab account_transaction">
            <?php include "tabs/businessflow/account_transaction.php" ?>
          </div>

        </div>

      </div>
    </div>
  </div>


    <!--core js-->
    <script src="<?php echo BASE_URL; ?>assets/js/jquery.min.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/draggabilly.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/loadingoverlay.js"></script>
    <!-- <script src="<?php echo BASE_URL; ?>assets/js/app.init.js"></script> -->
    <!-- <script src="<?php echo BASE_URL; ?>assets/js/app.min.js"></script> -->
    <script src="<?php echo BASE_URL; ?>assets/js/bootstrap.bundle.min.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/BootstrapMenu.min.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/theme.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/chrometab.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/sidebar.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/chairman.min.js"></script>
    <!--system js-->
    <!-- <script src="<?php echo BASE_URL; ?>assets/js/template.js"></script> -->
    <!-- <script src="<?php echo BASE_URL; ?>assets/js/account_transaction.js"></script> -->
    <!-- <script src="<?php echo BASE_URL; ?>assets/libs/apexcharts/dist/apexcharts.min.js"></script> -->
    <!-- <script src="<?php echo BASE_URL; ?>assets/js/dashboard.js"></script> -->
  
    <script src="<?php echo BASE_URL; ?>assets/js/datamap.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/tables.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/helper.js" defer></script>
    <script src="<?php echo BASE_URL; ?>assets/js/app.js" defer></script>
    <script src="<?php echo BASE_URL; ?>assets/js/handler.js" defer></script>
    <script src="https://unpkg.com/micromodal/dist/micromodal.min.js"></script>

    
    <script>
      MicroModal.init(); //modal

      const tabContainer = document.querySelector(".tab-container");
      const scrollLeftBtn = document.querySelector(".scroll-left");
      const scrollRightBtn = document.querySelector(".scroll-right");
      scrollLeftBtn.addEventListener("click", () => {
          tabContainer.scrollBy({ left: -150, behavior: "smooth" });
      });
      scrollRightBtn.addEventListener("click", () => {
          tabContainer.scrollBy({ left: 150, behavior: "smooth" });
      });

        // const themeToggle = document.getElementById('theme-toggle');
        // const html = document.documentElement;
        // // Check saved theme or system preference
        // const savedTheme = localStorage.getItem('theme') || (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
        // html.setAttribute('data-theme', savedTheme);

        // themeToggle.addEventListener('click', () => {
        //   const currentTheme = html.getAttribute('data-theme');
        //   const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
        //   html.setAttribute('data-theme', newTheme);
        //   localStorage.setItem('theme', newTheme);
        // });

    </script>
</body>

</html> 