<?php
if (session_status() == PHP_SESSION_NONE) {
  session_start();
}
isset($_SESSION['lang']) ? $_SESSION['lang'] : $_SESSION['lang'] = 'en';
$lang = $_SESSION['lang'];
$translator = include "tabs/lang/{$lang}.php";
//  print_r($lang);
!(new Controller)->isUserLoggedIn() ? header("location:../") : "";
 $adminEmail = (new Controller)->getSeesion("isUserLoggedIn");
 $fullname = (new Controller)->getUsername($adminEmail);
// echo $fullname['full_name'];

?>
<!DOCTYPE html>
<html oncontextmenu="return falsex" lang="en" dir="ltr" data-color-theme="Blue_Theme"
  data-layout="vertical" data-boxed-layout="full" data-card="shadow">

<head>
  <!-- Required meta tags -->
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon icon-->
  <link rel="shortcut icon" type="image/png"
    href="<?php echo BASE_URL; ?>assets/images/logos/favicon.png" />
  <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/toast/toast.css" />
  <!-- Core Css -->
  <link rel="stylesheet"
    href="<?php echo BASE_URL; ?>assets/css/styles.css" />
  <link rel="stylesheet"
    href="<?php echo BASE_URL; ?>assets/css/chrometab.css" />
  <link rel="stylesheet"
    href="<?php echo BASE_URL; ?>assets/css/sidebar.css" />

  <link rel="stylesheet"
    href="<?php echo BASE_URL; ?>assets/css/daterangepicker.css" />


  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

  <title>Limvo AdminX</title>
  <style>
    .chrome__tab {
      /* width: 400px;
        height: auto;
        border: solid 2px #ccc; */
      padding: 20px;
      display: none;
    }

    .chrome__tabb {
      /* width: 400px;
        height: auto;
        border: solid 2px #ccc; */
      padding: 20px;
      display: none;
    }


    .chromclass {
      border-top: solid 3px orangered !important;
    }

    .chrome-tab-drag-handle {
      cursor: pointer !important;
    }

    /* Custom Scrollbar for Webkit Browsers */
    .table-wrapper::-webkit-scrollbar {
      width: 5px;
      /* Slimmer scrollbar width */
      height: 5px;
      /* Slimmer scrollbar height for horizontal scrolling */
    }

    .table-wrapper::-webkit-scrollbar-track {
      background: #f1f1f1;
      /* Lighter background for track */
      border-radius: 5px;
    }

    .table-wrapper::-webkit-scrollbar-thumb {
      background-color: #ccc;
      /* Blue color for thumb */
      border-radius: 10px;
      cursor: pointer;
    }

    .table-wrapper::-webkit-scrollbar-thumb:hover {
      background-color: #aaa;
      /* Darker blue on hover */
    }

    /* Hide the default dropdown arrow */
    .hover-dropdown .dropdown-toggle::after {
      display: none;
    }

    /* Show the dropdown menu on hover */
    .hover-dropdown:hover .dropdown-menu {
      display: block;
    }

    /* Custom scrollbar for Firefox Browsers */
    .table-wrapper::-moz-scrollbar {
      width: 5px;
      /* Slimmer scrollbar width */
      height: 5px;
      /* Slimmer scrollbar height for horizontal scrolling */
    }



h1 {
  font-size: calc( 1em + 3vmin );
  font-weight: 500;
  color: rgb(132, 143, 165);
  --x-offset: -0.0625em;
  --y-offset: 0.0625em;
  --stroke: 0.025em;
  --background-color: white;
  --stroke-color: lightblue;
  
  text-shadow: 
    
    var(--x-offset)
    var(--y-offset)
    0px
    var(--background-color), 
    
    calc( var(--x-offset) - var(--stroke) )
    calc( var(--y-offset) + var(--stroke) )
    0px
    var(--stroke-color);
  
}
@supports ( text-shadow: 1px 1px 1px 1px black ) {
  h1 {
    text-shadow:
      
      var(--x-offset)
      var(--y-offset)
      0px
      0px
      var(--background-color), 
      
      var(--x-offset) 
      var(--y-offset)
      var(--stroke)
      0px
      var(--stroke-color);
    
  }
}

  </style>
      <style>
      /* :root {
        --bg-color: #F9F9F9;
        --text-color:rgb(29, 28, 28);
        --accent-color: #007bff;
        --border-color: #e0e0e0;
        --chairman-dark:#ffffff;
        --chairman-border-none:solid 1px #e0e0e0;
        --chairman-color:#f9f9f9;
        --chairman-tab-header:#ccc;
        --chairmantext-color:#000000;
        color-scheme: light;
      }
      
      [data-theme="dark"] {
        --bg-color: #1a1a1a;
        --text-color: #ffffff;
        --chairmantext-color: #ffffff;
        --chairman-tab-header:rgb(9, 9, 9,.2);
        --accent-color: #4da3ff;
        --border-color: #444444;
          color-scheme: dark;
        --chairman-dark:#202a36;
        --chairman-color:#202a36;
        --chairman-border-none:solid 1px #1c1e1f;
      }
      
      body {
        background: var(--chairman-dark);
        color: var(--text-color);
        transition: background 0.3s ease;
      }

      .col-md-6{
        padding: 10px;
        border-radius: 10px;
        background: var(--chairman-dark);
      }

      .maincard{
        padding: 10px;
        border-radius: 10px;
        background: var(--chairman-dark);
      }

      .sidebarm{
        background: var(--chairman-dark);
        color: var(--text-color);
        border: var(--chairman-border-none);
      }

      .accordion-header {
          background: var(--chairman-color);
          color: var(--text-color);
          cursor: pointer;
          height:40px;
          padding: 5px;
          transition: background-color 0.3s;
          box-shadow: rgba(0, 0, 0, 0.1) 0px 1px 2px 0px;
          margin: 2px;
      }

      .custom-list {
          background: var(--chairman-tab-header) !important;
          color: var(--text-color) !important;
      }

      .logodivider{
        background: var(--chairman-dark);
      }

      .chrome-tabs{
        background: var(--chairman-tab-header);
      }

      .chrome-tab-drag-handle{
        background: var(--chairman-dark);
      }

      .chrome-tab-title{
        color: var(--text-color) !important;
      }

      .chrome-tabs-bottom-bar{
        background: var(--chairman-dark) !important;
      }

      .card{
        background: var(--chairman-dark);
        color: var(--text-color);
      }
      
      button {
        padding: 10px;
        background: var(--accent-color);
        border: 2px solid var(--border-color);
        color: var(--text-color);
        cursor: pointer;
      } */
      </style>
</head>

<body>
  <div class="toast toast-onload align-items-center text-bg-primary border-0" role="alert" aria-live="assertive"
    aria-atomic="true">
    <div class="toast-body hstack align-items-start gap-6">
      <i class="ti ti-alert-circle fs-6"></i>
      <div>
        <h5 class="text-white fs-3 mb-1">Welcome to Limvo</h5>
        <h6 class="text-white fs-2 mb-0">Back Office Admin</h6>
      </div>
      <button type="button" class="btn-close btn-close-white fs-2 m-0 ms-auto shadow-none" data-bs-dismiss="toast"
        aria-label="Close"></button>
    </div>
  </div>
  <!-- Preloader -->
  <div class="preloader">
    <img src="<?php echo BASE_URL; ?>assets/images/logos/Screenshot.jpg" alt="loader" class="lds-ripple img-fluid" style="width:150px;height:60px"/>
  </div>
  <div id="main-wrapper">
    <!-- Sidebar Start -->
    <aside class="left-sidebar with-vertical sidebarm">
      <div><!-- ---------------------------------- -->
        <!-- Start Vertical Layout Sidebar -->
        <!-- ---------------------------------- -->
        <div class="brand-logo d-flex align-items-center justify-content-between">
          <a href="<?php echo BASE_URL; ?>main/index.html"
            class="text-nowrap logo-img">
            <h1>Limvo&reg</h1> 
            <!-- <img
              src="<?php echo BASE_URL; ?>assets/images/logos/limvo1.jpg" width="200"
              class="dark-logo" alt="Logo-Dark" /> -->

          </a>
          <a href="javascript:void(0)" class="sidebartoggler ms-auto text-decoration-none fs-5 d-block d-xl-none">
            <i class="ti ti-x"></i>
          </a>
        </div>
        <div class="logodivider"></div>
        <nav class="" data-simplebar>
        
          <ul id="sidebarnav">
          

            <?php include 'sidebar.php' ?>
            <!-- <button id="theme-toggle">🌓 Toggle Theme</button> -->
          </ul>
        </nav>
         <div class="mb-1" style="background-color:redl;position: fixed;bottom: 0;left:0;">
        <div class="p-3 mb-0 bg-white-subtle rounded mt-3" style="position:relative;background:#F9F9F9;border:solid 1px #eee">
          <div class="hstack gap-3">
            <div class="john-img">
              <img
                src="<?php echo BASE_URL; ?>assets/images/profile/user-1.jpg"
                class="rounded-circle" width="40" height="40" alt="modernize-img" />
            </div>
            <div class="john-title">
              <h6 class="mb-0 fs-4 fw-semibold"><?php echo $fullname['full_name']; ?></h6>
              <span class="fs-2"><?php echo $fullname['role']; ?></span>
            </div>
            <button class="border-0 bg-transparent text-primary ms-auto" tabindex="0" type="button" aria-label="logout" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="logout">
              <div class="dropdown" aria-label="logout" data-bs-toggle="tooltip" data-bs-placement="top"
                data-bs-title="Profile">
                <a class="dropdown-toggles" href="javascript:void(0)" role="button" id="dropdownMenuLink-1"
                  data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                  <i class='bx bx-dots-vertical-rounded'></i>
                </a>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuLink-1"
                  style="box-shadow: rgba(149, 157, 165, 0.2) 0px 8px 24px;">
                  <a class="dropdown-item kanban-item-edit cursor-pointer d-flex align-items-center gap-1"
                    href="javascript:void(0);">
                    <i class='bx bx-user-check'></i>Add User
                  </a>
                  <a class="dropdown-item kanban-item-edit cursor-pointer d-flex align-items-center gap-1"
                    href="javascript:void(0);">
                    <i class='bx bx-pencil'></i>Change Password
                  </a>
                  <a class="dropdown-item kanban-item-delete cursor-pointer d-flex align-items-center gap-1"
                    href="javascript:void(0);">
                    <i class="bx bx-trash fs-5"></i>Delete
                  </a>
                </div>
              </div>
            </button>
          </div>
        </div>

        <div class="btn-group bg-white-subtle rounded " role="group" style="width:100%;border:solid 1px #eee;color:#bbb;background-color:#F9F9F9">
          <button type="button" class="btn bg-white-subtle">
            <i class='bx bx-bell' style="font-size: 20px;"></i>
          </button>
          <button type="button" class="btn bg-white-subtle ">
            <a href="../admin/signout"> <i class='bx bx-power-off' style="font-size: 20px;"></i> </a>
          </button>
          <button type="button" class="btn bg-white-subtle ">
            <i class='bx bx-history' style="font-size: 20px;"></i>
          </button>
          <button type="button" class="btn bg-white-subtle">
            <i class='bx bx-cog' style="font-size: 20px;"></i>
          </button>

          <!-- Button with Tooltip -->
          <!-- <button type="button" class="btn bg-white-subtle" data-bs-toggle="tooltip" data-bs-placement="top" title="Languages">
          <i class='bx bx-flag' style="font-size: 20px;"></i>
        </button> -->

          <!-- Dropdown Menu -->
          <div class="dropdown hover-dropdown">
            <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false"
              data-bs-toggle="tooltip" data-bs-placement="top" title="Languages">
              <i class="bx bx-globe" style="font-size: 20px;"></i>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <li value="ch" class="lang">

                <a class="dropdown-item d-flex align-items-center" href="#">
                  <img src="<?php echo BASE_URL; ?>assets/images/profile/china.jpg" class="rounded-circle" width="20" height="20" alt="modernize-img" />
                  <span class="ms-2">Chinese</span>
                </a>
              </li>
              <li value="en" class="lang">
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <img src="<?php echo BASE_URL; ?>assets/images/profile/uk.jpg" class="rounded-circle" width="20" height="20" alt="modernize-img" />
                  <span class="ms-2">English</span>
                </a>
              </li>

            </ul>
          </div>

          <div id="translation-container" data-translations='<?= json_encode($translator); ?>'></div>
        </div>
        </div>
      

       

        <!-- ---------------------------------- -->
        <!-- Start Vertical Layout Sidebar -->
        <!-- ---------------------------------- -->
      </div>
    </aside>
    <!--  Sidebar End -->
    <div class="page-wrapper">

      <div class="containe-fluid">

        <div class="surface">
          <div class="mock-browser">
            <div class="chrome-tabs" style="--tab-content-margin: 9px">
              <div class="chrome-tabs-content">
                <div class="chrome-tab" id="tabhead" active>
                  <div class="chrome-tab-dividers"></div>
                  <div class="chrome-tab-background">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg">
                      <defs>
                        <symbol id="chrome-tab-geometry-left" viewBox="0 0 214 36">
                          <path d="M17 0h197v36H0v-2c4.5 0 9-3.5 9-8V8c0-4.5 3.5-8 8-8z" />
                        </symbol>
                        <symbol id="chrome-tab-geometry-right" viewBox="0 0 214 36">
                          <use xlink:href="#chrome-tab-geometry-left" />
                        </symbol>
                        <clipPath id="crop">
                          <rect class="mask" width="100%" height="100%" x="0" />
                        </clipPath>
                      </defs>
                      <svg width="52%" height="100%">
                        <use xlink:href="#chrome-tab-geometry-left" width="214" height="36"
                          class="chrome-tab-geometry" />
                      </svg>
                      <g transform="scale(-1, 1)">
                        <svg width="52%" height="100%" x="-100%" y="0">
                          <use xlink:href="#chrome-tab-geometry-right" width="214" height="36"
                            class="chrome-tab-geometry" />
                        </svg>
                      </g>
                    </svg>
                  </div>
                  <div class="chrome-tab-content">
                    <div class="chrome-tab-favicon" style="
                    background-image: url('demo/images/google-favicon.ico');
                  "></div>
                    <div class="chrome-tab-title"><?= $translator['DASHBOARD']; ?></div>
                    <div class="chrome-tab-holder" hidden>home</div>
                    <div class="chrome-tab-drag-handle chromclass"></div>
                    <div class="chrome-tab-close" hidden></div>
                  </div>
                </div>
              </div>
              <div class="chrome-tabs-bottom-bar"></div>
              <!-- Styles to prevent flash after JS initialization -->
            </div>
            <!-- <div class="chrome-tabs-optional-shadow-below-bottom-bar"></div> -->
          </div>
        </div>

        <div class="rowr" style="padding:0px;overflow-x:hidden;">

          <div class="chrome__tab home">
            <?php include "tabs/home.php" ?>
          </div>


          <div class="chrome__tab account_transaction">
            <?php include "tabs/businessflow/account_transaction.php" ?>
          </div>

          <div class="chrome__tab game_getting_statistics">
            <?php include "tabs/businessflow/game_getting_statistics.php" ?>
          </div>

          <div class="chrome__tab Lottery">
            <?php include "tabs/businessflow/lottery_betting_record.php" ?>
          </div>

          <div class="chrome__tab Track">
            <?php include "tabs/businessflow/trackbet.php" ?>
          </div>

          <div class="chrome__tab Deposit">
            <?php include "tabs/financialmanage/deposit.php" ?>
          </div>

          <div class="chrome__tab Finance">
            <?php include "tabs/financialmanage/finance_changes.php" ?>
          </div>

          <div class="chrome__tab Withdrawal">
            <?php include "tabs/financialmanage/withdrawal.php" ?>
          </div>

          <div class="chrome__tab Userlogs">
            <?php include "tabs/accountmanage/userlogs.php" ?>
          </div>

          <div class="chrome__tab Userlist">
            <?php include "tabs/accountmanage/userlist.php" ?>
          </div>

          <div class="chrome__tab Invitation">
            <?php include "tabs/promotionmanage/invitation_referallink.php" ?>
          </div>

          <div class="chrome__tab quota">
            <?php include "tabs/agentmanage/quota.php" ?>
          </div>

              <!--User Bank management-->
              <div class="chrome__tab  Bank">
             <?php include "tabs/userbank/bankcard.php" ?>
             </div>

          <!-- Report Management -->
           <div class="chrome__tab Win">
            <?php include "tabs/report_management/win_loss_report.php" ?>
           </div>
           <div class="chrome__tab NGPWin">
            <?php include "tabs/report_management/ngp_win_loss_report.php" ?>
           </div>

         


          <!--system managenet-->

          <div class="chrome__tab administrator_list">
            <?php include "tabs/system_management/administrator_list.php" ?>
          </div>

          <div class="chrome__tab backup_recovery">
            <?php include "tabs/system_management/backup_recovery.php" ?>
          </div>

        
          <!--game management-->
          <div class="chrome__tab  lottery_parameters">
            <?php include "tabs/game_management/lottery_parameters.php" ?>
          </div>

          <div class="chrome__tab  lottery_draw">
            <?php include "tabs/game_management/lottery_draws.php" ?>
          </div>

          
          <div class="chrome__tab  lottery_basic_params">
            <?php include "tabs/game_management/lottery_basic_param.php"?>
          </div>

        </div>

      </div>
      <script>
        function handleColorTheme(e) {
          document.documentElement.setAttribute("data-color-theme", e);
        }
      </script>

    </div>
    <div class="dark-transparent sidebartoggler"></div>

    <script src="<?php echo BASE_URL; ?>assets/js/vendor.min.js"></script>
    <!-- Import Js Files -->
    <script src="<?php echo BASE_URL; ?>assets/js/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/draggabilly.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/bootstrap.bundle.min.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/libs/simplebar/dist/simplebar.min.js"></script>


    <script src="<?php echo BASE_URL; ?>assets/js/app.init.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/theme.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/app.min.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/sidebarmenu.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/chrometab.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/pagination.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/sidebar.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/BootstrapMenu.min.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/toast/toast-plugin.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/libs/daterangepicker/moment.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/libs/daterangepicker/daterangepicker.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/libs/daterangepicker/daterangepicker.init.js"></script>


    <!--custom js-->
    <script src="<?php echo BASE_URL; ?>assets/js/chairman.min.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/template.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/account_transaction.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/lotterybet.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/trackbet.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/lottery_draws.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/admin_list.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/userlist.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/backup.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/userlogs.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/referrallink.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/quota.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/finance_change.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/deposit.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/withdrawal.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/bankcard.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/ggp_win_loss.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/ngp_win_loss.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/lottery_basic_params.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/lottery_parameters.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/lottery_draws.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/lang.js"></script>



    <script src="<?php echo BASE_URL; ?>assets/toast/toast-plugin.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/libs/daterangepicker/daterangepicker.init.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/libs/daterangepicker/daterangepicker.js"></script>

    <!-- Bootstrap 5 CSS (in the <head> of your HTML) -->


    <!-- Your HTML content goes here -->


    <!-- solar icons -->
    <script src="https://cdn.jsdelivr.net/npm/iconify-icon@1.0.8/dist/iconify-icon.min.js"></script>
    <script
      src="<?php echo BASE_URL; ?>assets/libs/apexcharts/dist/apexcharts.min.js">
    </script>
    <script src="<?php echo BASE_URL; ?>assets/js/dashboard.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@2.1.7/dist/loadingoverlay.min.js">
    </script>
    <script>

      // const themeToggle = document.getElementById('theme-toggle');
      //   const html = document.documentElement;
      //   // Check saved theme or system preference
      //   const savedTheme = localStorage.getItem('theme') || (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
      //   html.setAttribute('data-theme', savedTheme);

      //   themeToggle.addEventListener('click', () => {
      //     const currentTheme = html.getAttribute('data-theme');
      //     const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
      //     html.setAttribute('data-theme', newTheme);
      //     localStorage.setItem('theme', newTheme);
      //   });

      document.addEventListener('DOMContentLoaded', function() {
        const tableContainer = document.querySelector('.table-wrapper');
        const headerRow = document.querySelector('.accheaderrow');

        tableContainer.addEventListener('scroll', function() {
          if (tableContainer.scrollTop > 0) {
            headerRow.classList.add('sticky-header');
          } else {
            headerRow.classList.remove('sticky-header');
          }
        });

      });
     
    </script>
</body>

</html>