<?php 
(new SessionMan)->isUserLoggedIn() ? header("location:../") : "";
?>
<!DOCTYPE html>
<html lang="en" dir="ltr" data-bs-theme="light" data-color-theme="Blue_Theme" data-layout="vertical">

<head>
  <!-- Required meta tags -->
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!-- Favicon icon-->
  <link rel="shortcut icon" type="image/png" href="<?php echo BASE_URL; ?>assets/images/logos/favicon.png" />
  <!-- Core Css -->
  <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/toast/toast.css" />
  <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/styles.css" />
  <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/signin.css" />
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
  <title>Limvo Admin</title>
</head>

<body style="background-color:#F9F9F9">
  <!-- Preloader -->
  <!-- <div class="preloader">
    <img src="<?php echo BASE_URL; ?>assets/images/logos/favicon.png" alt="loader" class="lds-ripple img-fluid" />
  </div> -->
  <div class="top-right-box">
  <div class="btn-group mb-2 flagholder" role="group" aria-label="Basic example"
        style="border:solid 1px #eee;color:#bbb;background-color:#fff">
        <button id="en_lang" type="button" class="btn bg-white-subtle accplayer" value="left">
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 7410 3900" width="30" height="20"><path fill="#b22234" d="M0 0h7410v3900H0z"/><path d="M0 450h7410m0 600H0m0 600h7410m0 600H0m0 600h7410m0 600H0" stroke="#fff" stroke-width="300"/><path fill="#3c3b6e" d="M0 0h2964v2100H0z"/><g fill="#fff"><g id="d"><g id="c"><g id="e"><g id="b"><path id="a" d="M247 90l70.534 217.082-184.66-134.164h228.253L176.466 307.082z"/><use xlink:href="#a" y="420"/><use xlink:href="#a" y="840"/><use xlink:href="#a" y="1260"/></g><use xlink:href="#a" y="1680"/></g><use xlink:href="#b" x="247" y="210"/></g><use xlink:href="#c" x="494"/></g><use xlink:href="#d" x="988"/><use xlink:href="#c" x="1976"/><use xlink:href="#e" x="2470"/></g></svg>
        </button>
        <button id="zh_lang" type="button" class="btn bg-white-subtle accplayer" value="right">
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 30 20" width="30" height="20"><defs><path id="a" d="M0-1L.588.809-.952-.309H.952L-.588.809z" fill="#FF0"/></defs><path fill="#EE1C25" d="M0 0h30v20H0z"/><use xlink:href="#a" transform="matrix(3 0 0 3 5 5)"/><use xlink:href="#a" transform="rotate(23.036 .093 25.536)"/><use xlink:href="#a" transform="rotate(45.87 1.273 16.18)"/><use xlink:href="#a" transform="rotate(69.945 .996 12.078)"/><use xlink:href="#a" transform="rotate(20.66 -19.689 31.932)"/></svg>
        </button>
      </div>
  </div>
  <div id="main-wrapper" class="auth-customizer-none">
    <div class="position-relative overflow-hidden min-vh-100 w-100 d-flex align-items-center justify-content-center">
      <div class="d-flex align-items-center justify-content-center w-100">
        <div class="row justify-content-center w-100">

          <!-- start Sample Form with the Icons -->


          <div class="card col-md-8 col-lg-6 col-xxl-3"
            style="border-width: 1px 1px 50px 1px;  border-color:#ccc; box-shadow: rgba(0, 0, 0, 0.2) 0px 12px 28px 0px, rgba(0, 0, 0, 0.1) 0px 2px 4px 0px, rgba(255, 255, 255, 0.05) 0px 0px 0px 1px inset;">

            <div id="wifi-loader">
              <svg class="circle-outer" viewBox="0 0 86 86">
                <circle class="back" cx="43" cy="43" r="40"></circle>
                <circle class="front" cx="43" cy="43" r="40"></circle>
                <circle class="new" cx="43" cy="43" r="40"></circle>
              </svg>
              <svg class="circle-middle" viewBox="0 0 60 60">
                <circle class="back" cx="30" cy="30" r="27"></circle>
                <circle class="front" cx="30" cy="30" r="27"></circle>
              </svg>
              <svg class="circle-inner" viewBox="0 0 34 34">
                <circle class="back" cx="17" cy="17" r="14"></circle>
                <circle class="front" cx="17" cy="17" r="14"></circle>
              </svg>
              <div class="text" data-text="">o</div>
            </div>


            <div class="card-body">
              <h2 class="card-title"><b class="translatable" data-key="limvo_admin">Limvo Backoffice Admin</b></h2>
              <p class="card-subtitle mb-3 translatable" data-key="enzerhub_group">
                Enzerhub Coding Group.
              </p>
              <form autocomplete="offf">

                <div class="form-floating mb-3">
                  <input type="email" class="form-control email" placeholder="Email" autocomplete="New-Email" />
                  <label class="translatable" data-key="email">
                    <i class='bx bx-envelope' style="font-size: 20px;margin-right:5px"></i>Email
                    address
                  </label>
                </div>
                <div class="form-floating mb-3">
                  <input type="password" class="form-control password" placeholder="Password"
                    autocomplete="New-Password" />
                  <label class="translatable" data-key="password">
                    <i class='bx bx-lock' style="font-size: 20px;margin-right:5px"></i>Password
                  </label>
                </div>

                <div class="d-md-flex align-items-center">
                  <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="sf1" value="check" />
                    <label class="form-check-label translatable" data-key="remember_me" for="sf1">Remember Me</label>
                  </div>
                  <div class="mt-3 mt-md-0 ms-auto">
                    <button type="submit" class="signin btn  hstack gap-6" data-key="signing" style="border:solid 1px #ccc">
                      <i class='bx bx-check-shield load' style="font-size: 20px;"></i>
                      <span class="translatable" data-key="signing">Sign in</span>
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>


    <script src="<?php echo BASE_URL; ?>assets/js/jquery.min.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/bootstrap.bundle.min.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/index.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/toast/toast-plugin.js"></script>

</body>

</html>