<?php 
(new SessionMan)->isUserLoggedIn() ? header("location:../") : "";
?>
<!DOCTYPE html>
<html lang="en" dir="ltr" data-bs-theme="light" data-color-theme="Blue_Theme" data-layout="vertical">

<head>
  <!-- Required meta tags -->
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!-- Favicon icon-->
  <link rel="shortcut icon" type="image/png" href="<?php echo BASE_URL; ?>assets/images/logos/favicon.png" />
  <!-- Core Css -->
  <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/toast/toast.css" />
  <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/styles.css" />
  <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/signin.css" />
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
  <title>Limvo Admin</title>
</head>

<body style="background-color:#F9F9F9">
  <!-- Preloader -->
  <!-- <div class="preloader">
    <img src="<?php echo BASE_URL; ?>assets/images/logos/favicon.png" alt="loader" class="lds-ripple img-fluid" />
  </div> -->
  <div id="main-wrapper" class="auth-customizer-none">
    <div class="position-relative overflow-hidden min-vh-100 w-100 d-flex align-items-center justify-content-center">
      <div class="d-flex align-items-center justify-content-center w-100">
        <div class="row justify-content-center w-100">

          <!-- start Sample Form with the Icons -->


          <div class="card col-md-8 col-lg-6 col-xxl-3"
            style="border-width: 1px 1px 50px 1px;  border-color:#ccc; box-shadow: rgba(0, 0, 0, 0.2) 0px 12px 28px 0px, rgba(0, 0, 0, 0.1) 0px 2px 4px 0px, rgba(255, 255, 255, 0.05) 0px 0px 0px 1px inset;">

            <div id="wifi-loader">
              <svg class="circle-outer" viewBox="0 0 86 86">
                <circle class="back" cx="43" cy="43" r="40"></circle>
                <circle class="front" cx="43" cy="43" r="40"></circle>
                <circle class="new" cx="43" cy="43" r="40"></circle>
              </svg>
              <svg class="circle-middle" viewBox="0 0 60 60">
                <circle class="back" cx="30" cy="30" r="27"></circle>
                <circle class="front" cx="30" cy="30" r="27"></circle>
              </svg>
              <svg class="circle-inner" viewBox="0 0 34 34">
                <circle class="back" cx="17" cy="17" r="14"></circle>
                <circle class="front" cx="17" cy="17" r="14"></circle>
              </svg>
              <div class="text" data-text="">o</div>
            </div>


            <div class="card-body">
              <h2 class="card-title"><b>Limvo Backoffice Admin</b></h2>
              <p class="card-subtitle mb-3">
                Enzerhub Coding Group.
              </p>
              <form autocomplete="offf">

                <div class="form-floating mb-3">
                  <input type="email" class="form-control email" placeholder="Email" autocomplete="New-Email" />
                  <label>
                    <i class='bx bx-envelope' style="font-size: 20px;margin-right:5px"></i>Email
                    address
                  </label>
                </div>
                <div class="form-floating mb-3">
                  <input type="password" class="form-control password" placeholder="Password"
                    autocomplete="New-Password" />
                  <label>
                    <i class='bx bx-lock' style="font-size: 20px;margin-right:5px"></i>Password
                  </label>
                </div>

                <div class="d-md-flex align-items-center">
                  <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="sf1" value="check" />
                    <label class="form-check-label" for="sf1">Remember Me</label>
                  </div>
                  <div class="mt-3 mt-md-0 ms-auto">
                    <button type="submit" class="signin btn   hstack gap-6" style="border:solid 1px #ccc">
                      <i class='bx bx-check-shield load' style="font-size: 20px;"></i>
                      Sign in
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>


    <script src="<?php echo BASE_URL; ?>assets/js/jquery.min.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/bootstrap.bundle.min.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/js/index.js"></script>
    <script src="<?php echo BASE_URL; ?>assets/toast/toast-plugin.js"></script>

</body>

</html>