<?php 
session_start();;
(new Controller)->isUserLoggedIn() ? header("location:../") : "";
?>
<!DOCTYPE html>
<html lang="en" dir="ltr" data-bs-theme="light" data-color-theme="Blue_Theme" data-layout="vertical">

<head>
  <!-- Required meta tags -->
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!-- Favicon icon-->
  <link rel="shortcut icon" type="image/png" href="<?php echo BASE_URL; ?>assets/images/logos/favicon.png" />
  <!-- Core Css -->
  <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/toast/toast.css" />
  <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/styles.css" />
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
  <title>Limvo Admin</title>
  <style>

#wifi-loader {
  --background: #ccc;
  --front-color: #ccc;
  --back-color: #ccc;
  --text-color: #ccc;
  width: 64px;
  height: 64px;
  border-radius: 50px;
  position: relative;
  display: flex;
  justify-content: center;
  align-items: center;
}

#wifi-loader svg {
  position: absolute;
  display: flex;
  justify-content: center;
  align-items: center;
}

#wifi-loader svg circle {
  position: absolute;
  fill: none;
  stroke-width: 6px;
  stroke-linecap: round;
  stroke-linejoin: round;
  transform: rotate(-100deg);
  transform-origin: center;
}

#wifi-loader svg circle.back {
  stroke: var(--back-color);
}

#wifi-loader svg circle.front {
  stroke: var(--front-color);
}

#wifi-loader svg.circle-outer {
  height: 86px;
  width: 86px;
}

#wifi-loader svg.circle-outer circle {
  stroke-dasharray: 62.75 188.25;
}

#wifi-loader svg.circle-outer circle.back {
  animation: circle-outer135 1.8s ease infinite 0.3s;
}

#wifi-loader svg.circle-outer circle.front {
  animation: circle-outer135 1.8s ease infinite 0.15s;
}

#wifi-loader svg.circle-middle {
  height: 60px;
  width: 60px;
}

#wifi-loader svg.circle-middle circle {
  stroke-dasharray: 42.5 127.5;
}

#wifi-loader svg.circle-middle circle.back {
  animation: circle-middle6123 1.8s ease infinite 0.25s;
}

#wifi-loader svg.circle-middle circle.front {
  animation: circle-middle6123 1.8s ease infinite 0.1s;
}

#wifi-loader svg.circle-inner {
  height: 34px;
  width: 34px;
}

#wifi-loader svg.circle-inner circle {
  stroke-dasharray: 22 66;
}

#wifi-loader svg.circle-inner circle.back {
  animation: circle-inner162 1.8s ease infinite 0.2s;
}

#wifi-loader svg.circle-inner circle.front {
  animation: circle-inner162 1.8s ease infinite 0.05s;
}

#wifi-loader .text {
  position: absolute;
  bottom: -40px;
  display: flex;
  justify-content: center;
  align-items: center;
  text-transform: lowercase;
  font-weight: 500;
  font-size: 14px;
  letter-spacing: 0.2px;
}

#wifi-loader .text::before, #wifi-loader .text::after {
  content: attr(data-text);
}

#wifi-loader .text::before {
  color: var(--text-color);
}

#wifi-loader .text::after {
  color: var(--front-color);
  animation: text-animation76 3.6s ease infinite;
  position: absolute;
  left: 0;
}

@keyframes circle-outer135 {
  0% {
    stroke-dashoffset: 25;
  }

  25% {
    stroke-dashoffset: 0;
  }

  65% {
    stroke-dashoffset: 301;
  }

  80% {
    stroke-dashoffset: 276;
  }

  100% {
    stroke-dashoffset: 276;
  }
}

@keyframes circle-middle6123 {
  0% {
    stroke-dashoffset: 17;
  }

  25% {
    stroke-dashoffset: 0;
  }

  65% {
    stroke-dashoffset: 204;
  }

  80% {
    stroke-dashoffset: 187;
  }

  100% {
    stroke-dashoffset: 187;
  }
}

@keyframes circle-inner162 {
  0% {
    stroke-dashoffset: 9;
  }

  25% {
    stroke-dashoffset: 0;
  }

  65% {
    stroke-dashoffset: 106;
  }

  80% {
    stroke-dashoffset: 97;
  }

  100% {
    stroke-dashoffset: 97;
  }
}

@keyframes text-animation76 {
  0% {
    clip-path: inset(0 100% 0 0);
  }

  50% {
    clip-path: inset(0);
  }

  100% {
    clip-path: inset(0 0 0 100%);
  }
}
 
  </style>
</head>

<body style="background-color:#F9F9F9">
  <!-- Preloader -->
  <!-- <div class="preloader">
    <img src="<?php echo BASE_URL; ?>assets/images/logos/favicon.png" alt="loader" class="lds-ripple img-fluid" />
  </div> -->
  <div id="main-wrapper" class="auth-customizer-none">
    <div class="position-relative overflow-hidden min-vh-100 w-100 d-flex align-items-center justify-content-center">
      <div class="d-flex align-items-center justify-content-center w-100">
        <div class="row justify-content-center w-100" >

              <!-- start Sample Form with the Icons -->
     

              <div class="card col-md-8 col-lg-6 col-xxl-3" style="border-width: 1px 1px 50px 1px;  border-color:#ccc; box-shadow: rgba(0, 0, 0, 0.2) 0px 12px 28px 0px, rgba(0, 0, 0, 0.1) 0px 2px 4px 0px, rgba(255, 255, 255, 0.05) 0px 0px 0px 1px inset;">
              
              <div id="wifi-loader">
    <svg class="circle-outer" viewBox="0 0 86 86">
        <circle class="back" cx="43" cy="43" r="40"></circle>
        <circle class="front" cx="43" cy="43" r="40"></circle>
        <circle class="new" cx="43" cy="43" r="40"></circle>
    </svg>
    <svg class="circle-middle" viewBox="0 0 60 60">
        <circle class="back" cx="30" cy="30" r="27"></circle>
        <circle class="front" cx="30" cy="30" r="27"></circle>
    </svg>
    <svg class="circle-inner" viewBox="0 0 34 34">
        <circle class="back" cx="17" cy="17" r="14"></circle>
        <circle class="front" cx="17" cy="17" r="14"></circle>
    </svg>
    <div class="text" data-text="">o</div>
</div>
              
              
              <div class="card-body" >
                  <h2 class="card-title"><b>Limvo Backoffice Admin</b></h2>
                  <p class="card-subtitle mb-3">
                    Enzerhub Coding Group.
                  </p>
                  <form autocomplete="offf">

                    <div class="form-floating mb-3">
                      <input type="email" class="form-control email" placeholder="Email" autocomplete="New-Email"/>
                      <label>
                      <i class='bx bx-envelope' style="font-size: 20px;margin-right:5px" ></i>Email
                        address
                      </label>
                    </div>
                    <div class="form-floating mb-3">
                      <input type="password" class="form-control password" placeholder="Password" autocomplete="New-Password"/>
                      <label>
                      <i class='bx bx-lock' style="font-size: 20px;margin-right:5px" ></i>Password
                      </label>
                    </div>

                    <div class="d-md-flex align-items-center">
                      <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="sf1" value="check" />
                        <label class="form-check-label" for="sf1">Remember Me</label>
                      </div>
                      <div class="mt-3 mt-md-0 ms-auto">
                        <button type="submit" class="signin btn   hstack gap-6" style="border:solid 1px #ccc">
                        <!-- <i class='bx bx-check-shield' style="font-size: 20px;"></i> -->
                          Sign in
                        </button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
              <!-- end Sample Form with the Icons -->

              

         </div>
      </div>
    </div>

    <!-- Vertically centered modal -->
    <div class="modal fade" id="al-success-alert" tabindex="-1" aria-labelledby="vertical-center-modal" aria-hidden="true">
      <div class="modal-dialog modal-sm">
        <div class="modal-content modal-filled bg-white-subtle text-gray">
          <div class="modal-body p-4">
            <div class="text-center">
            <i class=' ' style="font-size:25px"></i>
              <h4 class="mt-2">Heads up!</h4>
              <p class="mt-3 maintext" style="color:#aaa"></p>
              <button type="button" class="btn btn-light my-2" data-bs-dismiss="modal">
                Okay
              </button>
            </div>
          </div>
        </div>
        <!-- /.modal-content -->
      </div>
    </div>

  <script src="<?php echo BASE_URL; ?>assets/js/jquery.min.js"></script>
  <script src="<?php echo BASE_URL; ?>assets/js/bootstrap.bundle.min.js"></script>
  <script src="<?php echo BASE_URL; ?>assets/js/theme.js"></script>
  <script src="<?php echo BASE_URL; ?>assets/js/admin.js"></script>
  <script src="<?php echo BASE_URL; ?>assets/toast/toast-plugin.js"></script>
  <!-- solar icons -->
  <!-- <script src="https://cdn.jsdelivr.net/npm/iconify-icon@1.0.8/dist/iconify-icon.min.js"></script> -->
</body>

</html>